version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 3
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
      exclude:
        - "github.com/grafana/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
    open-pull-requests-limit: 3
    cooldown:
      default-days: 7
      exclude:
        - "grafana/*"
