version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 14
      semver-patch-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
