---
# This file must be signed. You can do so with the `mage drone` command

kind: pipeline
type: docker
name:

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: grafana/grafana-plugin-ci:1.9.5
    commands:
      - mage --keep -v build

  - name: lint
    image: golangci/golangci-lint:v1.64.2
    commands:
      - golangci-lint run ./...

  - name: test
    image: grafana/grafana-plugin-ci:1.9.5
    commands:
      - mage --keep -v test

  - name: vuln check
    image: golang:1.24.2
    depends_on: [clone]
    commands:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

---
kind: signature
hmac: 96b53fa91bf5f81092fd0f4e8780122d2eaae5ab3c1be3908ae7178874db163a

...
