name: Dependabot reviewer
on: pull_request
permissions:
  pull-requests: write
  contents: write
jobs:
  call-workflow-passing-data:
    uses: grafana/security-github-actions/.github/workflows/dependabot-automerge.yaml@main
    with:
      packages-minor-autoupdate: '["github.com/aws/aws-sdk-go","github.com/aws/aws-sdk-go-v2","github.com/aws/aws-sdk-go-v2/config","github.com/aws/aws-sdk-go-v2/credentials","github.com/aws/aws-sdk-go-v2/feature/ec2/imds","github.com/aws/aws-sdk-go-v2/service/sts","github.com/aws/smithy-go","github.com/google/go-cmp","github.com/grafana/grafana-plugin-sdk-go","github.com/grafana/sqlds/v4","github.com/jpillora/backoff","github.com/magefile/mage","github.com/stretchr/testify"]'
      repository-merge-method: "squash"
